import { headers } from 'next/headers';
import { 
  parseAcceptLanguage, 
  DEFAULT_LOCALE 
} from '@/lib/i18n/language-utils';

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

/**
 * Detects locale from App Router context
 */
async function getLocale(): Promise<string> {
  try {
    const headersList = await headers();
    const acceptLanguage = headersList.get('accept-language');
    return parseAcceptLanguage(acceptLanguage);
  } catch {
    return DEFAULT_LOCALE;
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();
  const dir = ['ar', 'he', 'fa', 'ur'].includes(locale) ? 'rtl' : 'ltr';

  return (
    <html lang={locale} dir={dir}>
      <head>
        <meta httpEquiv="Content-Language" content={locale} />
      </head>
      <body>{children}</body>
    </html>
  );
}
